server:
  port: 9090
  servlet:
    context-path: /spring-mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.108:3306/akon_dev?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:

      initial-size: 10

      min-idle: 10

      max-active: 20

      max-wait: 6000

      validation-query: select 1 from dual

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 30000

      test-while-idle: true

      test-on-borrow: false

      test-on-return: false

      pool-prepared-statements: false

      max-open-prepared-statements: -1

mybatis:
  mapper-locations: classpath*:com/akon/spring/mysql/mapper/*.xml
logging:
  level:
    com.akon.spring.mysql.model: debug
